#Parameters specific to the NGRIP ice core
age_top_prior: -30. #age at the top of the sequence
age_top_sigma: 10. #Error on top age
depth_grid: #depth grid for the age calculation
    type: 'regular'
    start: &depth_start 8.
    end: &depth_end 3084.
    resolution: 1.
age_truncation:
    inf: ~
    sup: 130000.